server: 
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://dpg-d17ls2ndiees73894ceg-a.oregon-postgres.render.com:5432/automobilecrud
        username: automobilecrud_user
        password: gk21XLBqdSkHS2Kmpfva2yUrbuoT7udO
        driver-class-name: org.postgresql.Driver
        initialize: true
    
    jpa:
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true
        
    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres
